AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Disable documentation requirement for matchers
Style/Documentation:
  Enabled: false

# Allow longer blocks in matchers, specs, and gemspec
Metrics/BlockLength:
  Exclude:
    - "lib/zenspec/matchers/**/*"
    - "spec/**/*"
    - "*.gemspec"

# Allow longer modules for matchers
Metrics/ModuleLength:
  Exclude:
    - "lib/zenspec/matchers/**/*"

# Allow constant definitions in test blocks
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"
